vmware-tanzu/application-accelerator-samples

- fragments/tap-workload/accelerator.yaml
This is a workaround for the OpenRewrite integration bug which filters out files without modifications. This occurs if a branch name passed as an option is the same as the branch name in the host accelerator.yaml.
Merge solution doesn't work because NWayDiff is not able to merge unrelated changes.
> Replace OpenRewriteRecipe with ReplaceText for the git repo branch replacement and removal of git repo subPath.

- appsso-starter-java/accelerator.yaml
- java-function/accelerator.yaml
- node-express/accelerator.yaml
- node-function/accelerator.yaml
- node-function/config/workload.yaml
- python-function/accelerator.yaml
- python-function/config/workload.yaml
- spring-cloud-serverless/accelerator.yaml
- tanzu-java-web-app/accelerator.yaml
- tap-initialize/accelerator.yaml
- weatherforecast-csharp/accelerator.yaml
- weatherforecast-steeltoe/accelerator.yaml
All accelerators are changed, except the following, as those are multi module projects which need `subPath` feature to work:
- `hungryman`
- `spring-smtp-gateway`
> Integrate tap-workload fragment to support GIT repository creation feature.

- where-for-dinner/where-for-dinner-ui/src/App.js
The main application UI landing page had the term Hungryman in the text; this has been removed.  Also fixed mis-spelling of continuously.
> Removing reference to name Hungryman

- appsso-starter-java/config/workload.yaml
- java-rest-service/config/workload-api-provider.yaml
- java-rest-service/config/workload-basic.yaml
- java-server-side-ui/config/workload.yaml
- node-express/config/workload.yaml
- node-function/config/workload.yaml
- python-function/config/workload.yaml
- spring-cloud-serverless/kubernetes/tap/workload.yaml
- spring-smtp-gateway/smtp-gateway/config/workload.yaml
- spring-smtp-gateway/smtp-sink/config/workload.yaml
- spring-smtp-gateway/templates/workloads.template
- tanzu-java-web-app/config/workload.yaml
- weatherforecast-csharp/config/workload.yaml
- weatherforecast-steeltoe/config/workload.yaml
- where-for-dinner/where-for-dinner-api-gateway/config/workload.yaml
- where-for-dinner/where-for-dinner-availability/config/workload.yaml
- where-for-dinner/where-for-dinner-crawler/config/workload.yaml
- where-for-dinner/where-for-dinner-notify/config/workload.yaml
- where-for-dinner/where-for-dinner-search-proc/config/workload.yaml
- where-for-dinner/where-for-dinner-search/config/workload.yaml
For mono repositories changed the `subPath` to not take into account the parent directory (which would not exist in target repository/file-system structure after generation).
> Removed the subPath in TAP workload.yaml for non-mono repositories

- java-rest-service/config/test-pipeline.yaml
- java-rest-service/config/workload-api-provider.yaml
- java-rest-service/config/workload-basic.yaml
and referred to this one from the workload definition. This allows users to have multiple Tekton (Test) pipelines provisioned on a TAP build/iterate cluster, as the 'test' label is too generic.
> Changed name and label of Tekton Test pipeline for Tanzu Java Rest Service

- python-function/accelerator.yaml
When the python-function accelerator was generating a config/workload.yaml file, it was not setting the BP_FUNCTION environment variable to the provided "Default function name".
> Fix python function name replacement in workload.yaml

- angular-frontend/nginx.conf
as part of the configuration, this is already provided by the corresponding Buildpack as startup parameter.
> Changed nginx.conf of angular-frontend to not have process-ID 

- where-for-dinner/where-for-dinner-api-gateway/config/workload.yaml
- where-for-dinner/where-for-dinner-availability/config/workload.yaml
- where-for-dinner/where-for-dinner-notify/config/workload.yaml
- where-for-dinner/where-for-dinner-search-proc/config/workload.yaml
- where-for-dinner/where-for-dinner-search/config/workload.yaml
Individual app workload configs have the incorrect app.kubernetes.io/part-of label.
Addressing #121
> Updating app.kubernetes.io/part-of labels in where for dinner apps.

- fragments/tap-workload/accelerator.yaml
- spring-smtp-gateway/accelerator.yaml
- where-for-dinner/accelerator.yaml
Apply it to 'where-for-dinner' and 'spring-smtp-gateway' Accelerator.
> Adjust 'tap-workload' Fragment to support multi-module repos by no deleting a 'source.git.subPath' property from workload.yaml.

- demo-input-types/accelerator.yaml
- demo-input-types/results.yaml
Fix https://github.com/pivotal/acc-content/issues/57
> Add custom type example to demo-input-types

- fragments/spring-boot-mysql/accelerator.yaml
- fragments/spring-boot-postgresql/accelerator.yaml
Those blocks referred to option names that are not in the transitive closure of what those fragments "saw" as options. Those were names that could be present in the *importing* accelerators, but this is wrong usage and caused inconsistencies at runtime.
> Remove dependsOn block that refers to not visible options

- weatherforecast-steeltoe/Tiltfile
- allows workloads applied using this weatherforecast-steeltoe tiltfile to be remotely debugged from Visual Studio by asking the build system to add the VS debug agent ("vsdbg")
- prevents having to re-apply workloads created via live update before they're able to be remotely debugged; vsdbg should always be present in the container for .NET workloads
- more info on this env var [here](https://paketo.io/docs/howto/dotnet-core/#enable-remote-debugging)
Signed-off-by: Andrew Woosnam <awoosnam@vmware.com>
> add BP_DEBUG_ENABLED env var to tiltfile

- java-rest-service/README.md
- java-rest-service/accelerator.yaml
* Removes database type option - this was added back by accident in a rebase
* Adds BP_JVM_VERSION to the build-env, this ensures deployments succeed when the java version is something other than 11
* Makes use of input values in the README
> Java Rest Service option cleanup

- namespace-provisioner-gitops-examples/LICENSE
- namespace-provisioner-gitops-examples/README.md
- namespace-provisioner-gitops-examples/custom-resources/random/data-values-configmap.yaml
- namespace-provisioner-gitops-examples/custom-resources/scanpolicies/snyk-scanpolicies.yaml
- namespace-provisioner-gitops-examples/custom-resources/tekton-pipelines/angular-test.yaml
- namespace-provisioner-gitops-examples/custom-resources/tekton-pipelines/golang-test.yaml
- namespace-provisioner-gitops-examples/custom-resources/tekton-pipelines/python-test.yaml
- namespace-provisioner-gitops-examples/custom-resources/testing-scanning-supplychain/grype-scan-policy.yaml
- namespace-provisioner-gitops-examples/custom-resources/testing-scanning-supplychain/tekton-pipeline-java.yaml
- namespace-provisioner-gitops-examples/custom-resources/workload-sa/workload-sa-with-secrets.yaml
- namespace-provisioner-gitops-examples/default-resources-overrides/overlays/sa-secrets.lib.yaml
- namespace-provisioner-gitops-examples/desired-namespaces/gitops-managed-desired-namespaces.yaml
Namespace provisioner for Tanzu Application Platform provides an easy, secure, automated way for Platform Operators to provision namespaces with the resources and proper namespace-level privileges required for their workloads to function as intended.
This PR adds the examples meant to be used in the component documentation and for use reference.
> add namespace provisioner examples for gitops

- where-for-dinner/accelerator.yaml
The last PR caused a bunch of TAP-specific files that we'd been excluding to start showing up in the accelerator. This fixes that and removes the transforms for those files.
> ASA fix where for dinner file inclusions 

- java-rest-service/accelerator.yaml
- tanzu-java-web-app/accelerator.yaml
- this avoids the issue where UI still shows a java version that will be overridden in engine processing but the user has no way change it to 17
> Remove javaVersion dependsOn updateBoot3

- weatherforecast-csharp/accelerator.yaml
- weatherforecast-steeltoe/accelerator.yaml
> Use compiler-safe(r) namespaces in C# projects

- where-for-dinner/doc/TAPDeployment.md
- where-for-dinner/templates/workloads.yaml
A previous error in the Jammy `base` cluster builder was missing the web server buildpack requiring the UI app to need the `full` clusterbuilder.  This has since been resolved in version 1.10.3 of the tanzu build service package, and the UI app will again build successfully using the `base` cluster builder.
> Removing full cluster builder dependency from Where For Dinner UI

- angular-frontend/package-lock.json
- react-frontend/package-lock.json
- where-for-dinner/where-for-dinner-ui/package-lock.json
Update TAP 1.5.0 with dependabot fixes.
This is cherry-pick of:
6bcfa6a Update where-for-dinner UI webpack dependency
caee457 Update React webpack dependency
57955da Update Angular dependencies
> Webpack version updates for TAP 1.5.0

- .github/tests/.grype.yaml
- .github/tests/angular-frontend-1/scan.sh
- .github/tests/appsso-starter-java-1/scan.sh
- .github/tests/csharp-rest-service-1/scan.sh
- .github/tests/generate.sh
- .github/tests/java-rest-service-boot3/scan.sh
- .github/tests/java-rest-service-gradle+flyway+mysql/scan.sh
- .github/tests/java-rest-service-gradle+liquibase+h2/scan.sh
- .github/tests/java-rest-service-gradle+liquibase+postgres/scan.sh
- .github/tests/java-rest-service-maven+flyway+h2/scan.sh
- .github/tests/java-rest-service-maven+flyway+postgres/scan.sh
- .github/tests/java-rest-service-maven+liquibase+mysql/scan.sh
- .github/tests/java-server-side-ui-gradle+sso/scan.sh
- .github/tests/java-server-side-ui-maven+nosso/scan.sh
- .github/tests/node-express-1/scan.sh
- .github/tests/react-frontend-1/scan.sh
- .github/tests/scan.sh
- .github/tests/spring-cloud-serverless-1/scan.sh
- .github/tests/spring-smtp-gateway-1/scan.sh
- .github/tests/tanzu-java-web-app-boot2/scan.sh
- .github/tests/tanzu-java-web-app-boot3/scan.sh
- .github/tests/weatherforecast-csharp-1/scan.sh
- .github/tests/weatherforecast-steeltoe-1/scan.sh
- .github/tests/where-for-dinner-1/scan.sh
Closes https://github.com/pivotal/acc-release/issues/490
note: The samples csharp-rest-service and weatherforecast-steeltoe fail the vulnerability scan. We could use help from someone with C# expertise to help resolve them.
> Add Grype scanning to accelerator samples

- ns-provisioner-samples/testing-scanning-supplychain-polyglot/tekton-pipeline-golang.yaml
- ns-provisioner-samples/testing-scanning-supplychain-polyglot/tekton-pipeline-java.yaml
- ns-provisioner-samples/testing-scanning-supplychain-polyglot/tekton-pipeline-nodejs.yaml
Namespace provisioner for Tanzu Application Platform provides an easy, secure, automated way for Platform Operators to provision namespaces with the resources and proper namespace-level privileges required for their workloads to function as intended.
This PR updates an examples meant to be used in the component documentation and for use reference.
> updates Namespace Provisioner samples of polyglot testing pipelines for TAP 1.5 

- appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/AppSSOAcceleratorApplication.java
- appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/IssuerTrust.java
- appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/WebSecurityConfig.java
On launch of `appsso-starter-java` accelerator, an initial connection is established with an AppSSO `AuthServer`. If the connection is over TLS and the AuthServer is serving a certificate issued by a non-public CA, the accelerator fails to launch with a rather cryptic error message. This PR seeks to address the error message issue by capturing the exception and producing a legible error message of what the exact issue is and how to rectify.
> Add AuthServer trust verification for appsso-starter-java

- where-for-dinner/where-for-dinner-availability/config/workload.yaml
- where-for-dinner/where-for-dinner-notify/config/workload.yaml
- where-for-dinner/where-for-dinner-search-proc/config/workload.yaml
- where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml
- where-for-dinner/where-for-dinner-search/config/workload.yaml
- where-for-dinner/where-for-dinner-search/src/main/resources/application.yml
Also aligning service claimss for RabbitMQ in individual workload.yaml files to use `ClassClaim` instead of `ResourceClaim` to match the config in app-operator directory (which uses `ClassClaim`)
Addressing issues #263 and #262.
> Supporting TLS Redis connection and fixing Pollable bean.

- ns-provisioner-samples/credentials/git.yaml
Namespace provisioner for Tanzu Application Platform provides an easy, secure, automated way for Platform Operators to provision namespaces with the resources and proper namespace-level privileges required for their workloads to function as intended.
This PR updates an example used in the component documentation to use `password` from `data.values.imported` instead of token.
> updates nsp sample git secret to reference password instead of token

- csharp-rest-service/Tiltfile
- fragments/live-update/Tiltfile
- java-function/Tiltfile
- node-function/Tiltfile
- python-web-app/Tiltfile
- spring-cloud-serverless/kubernetes/tap/Tiltfile
- spring-smtp-gateway/smtp-gateway/Tiltfile
- spring-smtp-gateway/smtp-sink/Tiltfile
- tanzu-java-web-app/Tiltfile
- tanzu-java-web-app/Tiltfile_gradle_intellij
- tanzu-java-web-app/Tiltfile_gradle_vscode
- weatherforecast-steeltoe/Tiltfile
- where-for-dinner/where-for-dinner-api-gateway/Tiltfile
- where-for-dinner/where-for-dinner-availability/Tiltfile
- where-for-dinner/where-for-dinner-crawler-python/Tiltfile
- where-for-dinner/where-for-dinner-notify/Tiltfile
- where-for-dinner/where-for-dinner-search-proc/Tiltfile
- where-for-dinner/where-for-dinner-search/Tiltfile
The vscode and intellij extensions will now pass the Tiltfile two new env vars: `WAIT_TIMEOUT` and `TYPE`.
This is to utilize the `--wait-timeout` and `--type` flags
> feat: add --wait-timeout and --type flags to Tiltfiles

- where-for-dinner/where-for-dinner-api-gateway/pom.xml
- where-for-dinner/where-for-dinner-api-gateway/src/main/resources/application.yaml
- where-for-dinner/where-for-dinner-availability/pom.xml
- where-for-dinner/where-for-dinner-availability/src/test/java/com/java/example/tanzu/wherefordinner/TestContainerConfiguration.java
- where-for-dinner/where-for-dinner-availability/src/test/java/com/java/example/tanzu/wherefordinner/WhereForDinnerAvailabilityTestApplication.java
- where-for-dinner/where-for-dinner-crawler/pom.xml
- where-for-dinner/where-for-dinner-notify/pom.xml
- where-for-dinner/where-for-dinner-notify/src/test/java/com/java/example/tanzu/wherefordinner/TestContainerConfiguration.java
- where-for-dinner/where-for-dinner-notify/src/test/java/com/java/example/tanzu/wherefordinner/WhereForDinnerNotifyTestApplication.java
- where-for-dinner/where-for-dinner-search-proc/pom.xml
- where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml
- where-for-dinner/where-for-dinner-search-proc/src/test/java/com/java/example/tanzu/wherefordinner/TestContainerConfiguration.java
- where-for-dinner/where-for-dinner-search-proc/src/test/java/com/java/example/tanzu/wherefordinner/WhereForDinnerSearchProcTestApplication.java
- where-for-dinner/where-for-dinner-search/pom.xml
- where-for-dinner/where-for-dinner-search/src/main/java/com/java/example/tanzu/wherefordinner/WhereForDinnerResApplication.java
- where-for-dinner/where-for-dinner-search/src/test/java/com/java/example/tanzu/wherefordinner/TestContainerConfiguration.java
- where-for-dinner/where-for-dinner-search/src/test/java/com/java/example/tanzu/wherefordinner/WhereForDinnerResTestApplication.java
- where-for-dinner/where-for-dinner-search/src/test/resources/application.yml
Updating Spring Boot version to 3.1.2
Adding test application classes to utilize new 3.1.0 TestContainer features when in IDE and command line dev mode.
> Updating Where For Dinner to Spring Boot 3.1.2

- java-rest-service/accelerator.yaml
Adding back java-version fragment to let MSFT test fragments in ASA. 
- java-rest-service was the only accelerator using java versions. I didn't find any other accelerator needing this fragment.
- Also, I didn't find any other useful fragment for ASA. please let me know if there is any.
> Uses java-version fragment in java-rest-service accelerator

- java-function/README.md
- node-function/README.md
- python-function/README.md
The function buildpacks are deprecated from TAP 1.7 and up.
> add warning to the function accelerators

- ns-provisioner-samples/testing-scanning-supplychain-multiple-scanners/tekton-pipeline-java.yaml
- ns-provisioner-samples/testing-scanning-supplychain-parameterized/tekton-pipeline-golang.yaml
- ns-provisioner-samples/testing-scanning-supplychain-parameterized/tekton-pipeline-java.yaml
- ns-provisioner-samples/testing-scanning-supplychain-parameterized/tekton-pipeline-nodejs.yaml
- ns-provisioner-samples/testing-scanning-supplychain-polyglot/tekton-pipeline-golang.yaml
- ns-provisioner-samples/testing-scanning-supplychain-polyglot/tekton-pipeline-java.yaml
- ns-provisioner-samples/testing-scanning-supplychain-polyglot/tekton-pipeline-nodejs.yaml
- ns-provisioner-samples/testing-scanning-supplychain/tekton-pipeline-java.yaml
- ns-provisioner-samples/testing-supplychain/tekton-pipeline-java.yaml
This PR adds the following `securityContext` to all tekton pipeline examples in Namespace provisioner samples folder so the pipeline can run in restricted tkgm environments.
```yaml
stepTemplate:
securityContext:
allowPrivilegeEscalation: false
runAsUser: 1000
runAsNonRoot: true
capabilities:
drop:
- ALL
seccompProfile:
type: RuntimeDefault
```
> fix: added securityContext so the pipeline runs in restricted environments

- ns-provisioner-samples/tanzu-supply-chain/buildpack-build-clusterrolebinding.yaml
- ns-provisioner-samples/tanzu-supply-chain/oci-store-credentials.yaml
- ns-provisioner-samples/tanzu-supply-chain/oci-store.yaml
This MR adds a sample folder called tanzu-supply-chain in Namespace provisioner samples which creates 3 things
* OCI store secret
* Credentials for that OCI store 
* ClusterRoleBinding for buildpack build component
> feat: Add namespace provisioner samples for setting up Tanzu Supply Chains

- java-server-side-ui/build.gradle.kts
- java-server-side-ui/pom.xml
- align build.gradle.kts with pom.xml, using webjars and webjars bootstrap
- unpin webjars-locator-core version in pom.xml, the dependency is managed by spring boot dependency management
> java-server-side-ui: include webjars in gradle build file

- where-for-dinner/templates/workloads.yaml
- where-for-dinner/where-for-dinner-crawler-python/config/workload.yaml
- where-for-dinner/where-for-dinner-crawler/config/workload.yaml
- where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml
Search processor configuration defaults to calling the crawler service on port 8080.  When Eureka is enabled, the configuration excludes the port and lets the service registry take over.
> Updating crawler server to user service port 8080.

- spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/boot/SmtpGatewayApplication.java
Because the spring conventions are detecting the actuator library, the web interface also needs to be enabled for the added probes to work corrects; otherwise K8s will kill the app because it doesn't think the app is responsive (probes failing).
> Enabling the SMTP Gateway web interface to allow for scraping.

- where-for-dinner/.tanzu/config/k8sGatewayRoutes.yaml
Update the httproute on the where-for-dinner sample app used as part of the quick start for Tanzu Platform for Kubernetes to use ingress v2 spec.
> Update httproute for ingress v2
