java-rest-service/accelerator.yaml, java-rest-service/config/workload-api-provider.yaml, java-rest-service/config/workload-basic.yaml, java-rest-service/config/workload.yaml
Follow up from: https://github.com/pivotal/acc-content/pull/35.  Major change was to create 2 separate workload file templates: one for auto registration and one without auto registration
=> Api auto reg

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Signed-off-by: Thomas Risberg <risbergt@vmware.com>
=> Update project name

hungryman/doc/TAPDeployment.md, spring-smtp-gateway/smtp-gateway/catalog/catalog.yaml, spring-smtp-gateway/smtp-gateway/config/workload.yaml, spring-smtp-gateway/smtp-sink/catalog/catalog.yaml, spring-smtp-gateway/smtp-sink/config/workload.yaml
Signed-off-by: Thomas Risberg <risbergt@vmware.com>
=> Update any remaining sample-accelerators URLs

appsso-starter-java/config/workload.yaml, hungryman/hungryman-api-gateway/config/workload.yaml, hungryman/hungryman-crawler/config/workload.yaml, hungryman/hungryman-notify/config/workload.yaml, hungryman/hungryman-search-proc/config/workload.yaml, hungryman/hungryman-search/config/workload.yaml, hungryman/templates/workloads.yaml, node-express/config/workload.yaml, spring-smtp-gateway/templates/workloads.template, tanzu-java-web-app/config/workload.yaml, weatherforecast-csharp/config/workload.yaml, weatherforecast-steeltoe/config/workload.yaml
Signed-off-by: Thomas Risberg <risbergt@vmware.com>
=> Make all Git URLs consistent

hungryman/catalog/components/hungryman-api-gateway/hungryman-api-gateway.yaml, hungryman/catalog/components/hungryman-availability/hungryman-availability.yaml, hungryman/catalog/components/hungryman-notify/hungryman-notify.yaml, hungryman/catalog/components/hungryman-search-proc/hungryman-search-proc.yaml, hungryman/catalog/components/hungryman-search/hungryman-search.yaml, hungryman/catalog/components/hungryman-ui/hungryman-ui.yaml, hungryman/templates/workloads.yaml, spring-smtp-gateway/smtp-gateway/config/workload.yaml, spring-smtp-gateway/smtp-sink/config/workload.yaml
Also changing branch name to "main" from "secure-ui" for hungryman-ui when the secure option is selected.  The secure option is listed as experimental and is not fully tested and verified.
=> Fixing workload type in individual project config files for live updates

fragments/spring-boot-app-sso-auth-code-flow/accelerator.yaml, java-server-side-ui/src/main/resources/templates/index.html
Move login button triggering OIDC flow from `java-server-side-ui` accelerator to the `app-sso-auth-code-flow` fragment. This provides flexibility to add this button to any accelerator which includes this fragment.
=> Move login button triggering OIDC flow from java-server-side-ui accelerator to the app-sso-auth-code-flow fragment

appsso-starter-java/build.gradle, hungryman/hungryman-api-gateway/pom.xml, hungryman/hungryman-availability/pom.xml, hungryman/hungryman-crawler/pom.xml, hungryman/hungryman-notify/pom.xml, hungryman/hungryman-search-proc/pom.xml, hungryman/hungryman-search/pom.xml, hungryman/pom.xml, java-function/build.gradle, java-function/cloudevents/build.gradle, java-rest-service/build.gradle.kts, java-rest-service/pom.xml, java-server-side-ui/build.gradle.kts, java-server-side-ui/pom.xml, spring-cloud-serverless/pom.xml, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml, tanzu-java-web-app/pom.xml
Update dependencies:
- Upgraded to Spring Boot v2.7.4 to all Spring Boot based accelerators
- Override managed dependency of SnakeYaml to v1.32 which fixes several CVEs.
Co-authored-by: Dmitry Belyaev <dbelyaev@vmware.com>
=> Update dependencies for Java samples

weatherforecast-steeltoe/Program.cs, weatherforecast-steeltoe/Sample.csproj, weatherforecast-steeltoe/StaticFiles/index.html
fixes #56 and removes a couple NuGet references that aren't needed
=> Fix title and remove excess package references from Steeltoe sample

node-function/Tiltfile, node-function/k8s-resource.yaml
Signed-off-by: Joe Eltgroth <jeltgroth@vmware.com>
=> Enable Tilt to live update

java-rest-service/accelerator.yaml
=> Restored the addition of config/test-pipeline.yaml for java-rest-service

spring-smtp-gateway/smtp-gateway/Tiltfile, spring-smtp-gateway/smtp-sink/Tiltfile
- Changing port forward ports to 1026 instead of 1025
- Updating name of source image in smtp-gateway
- Fixing pod selectors in smtp-gateway and sink in tiltfiles
Addressing items in issue #63
=> Fixing tilt files:

java-function/DEPLOYING.md, python-function/DEPLOYING.md, python-function/config/workload.yaml, python-function/func.yaml
Update function docs to rely on environment variable instead of func.yaml
Signed-off-by: Joe Eltgroth <jeltgroth@vmware.com>
=> Update function docs to rely on environment variable instead of func.yaml

appsso-starter-java/config/workload.yaml, java-function/config/workload.yaml, java-rest-service/config/workload-api-provider.yaml, java-rest-service/config/workload-basic.yaml, java-server-side-ui/config/workload.yaml, node-express/config/workload.yaml, node-function/config/workload.yaml, python-function/config/workload.yaml, spring-cloud-serverless/kubernetes/tap/workload.yaml, spring-smtp-gateway/smtp-gateway/config/workload.yaml, spring-smtp-gateway/smtp-sink/config/workload.yaml, spring-smtp-gateway/templates/workloads.template, tanzu-java-web-app/config/workload.yaml, weatherforecast-csharp/config/workload.yaml, weatherforecast-steeltoe/config/workload.yaml, where-for-dinner/doc/TAPDeployment.md, where-for-dinner/templates/workloads.yaml, where-for-dinner/where-for-dinner-api-gateway/config/workload.yaml, where-for-dinner/where-for-dinner-availability/config/workload.yaml, where-for-dinner/where-for-dinner-crawler/config/workload.yaml, where-for-dinner/where-for-dinner-notify/config/workload.yaml, where-for-dinner/where-for-dinner-search-proc/config/workload.yaml, where-for-dinner/where-for-dinner-search/config/workload.yaml
Related to https://github.com/pivotal/acc-content/issues/62
=> Replace sample git repo url with placeholder

spring-smtp-gateway/doc/TAPDeployment.md, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/server/SafelistedServerSocket.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/springconfig/SMTPServerBeanConfig.java, spring-smtp-gateway/smtp-gateway/src/test/java/com/java/example/smtpmq/gateway/boot/SafelistedServerSocket_authCidrTest.java, spring-smtp-gateway/smtp-gateway/src/test/java/com/java/example/smtpmq/gateway/boot/SafelistedServerSocket_multiAuthCidrTest.java, spring-smtp-gateway/smtp-gateway/src/test/java/com/java/example/smtpmq/gateway/boot/SafelistedServerSocket_noauthCidrTest.java, spring-smtp-gateway/smtp-gateway/src/test/resources/properties/testLocalAuthorizedCIDRConfig.properties, spring-smtp-gateway/smtp-gateway/src/test/resources/properties/testLocalMultiAuthorizedCIDRConfig.properties, spring-smtp-gateway/smtp-gateway/src/test/resources/properties/testLocalNoAuthorizedCIDRConfig.properties, spring-smtp-gateway/smtp-sink/pom.xml
Also updating to Spring Boot 2.7.5 and Spring Cloud 2021.0.4.
Addressing issue #108
=> Changing "Whitelist" to "Safelist" in SMTP Gateway application.

fragments/spring-boot-mysql/accelerator.yaml, fragments/spring-boot-mysql/config/mysql-resource-claim-policy.yaml, fragments/spring-boot-mysql/config/mysql-resource-claim.yaml, fragments/spring-boot-mysql/config/mysql.yaml, fragments/spring-boot-postgresql/accelerator.yaml, fragments/spring-boot-postgresql/config/postgres-resource-claim-policy.yaml, fragments/spring-boot-postgresql/config/postgres-resource-claim.yaml, fragments/spring-boot-postgresql/config/postgres.yaml, java-rest-service/config/test-pipeline.yaml, java-rest-service/src/main/java/com/vmware/tap/accelerators/restservicedb/data/CustomerProfileEntity.java
Also, allow the user to select the storage class name.
=> Upgraded java-rest-service to use Service Claim instead of direct binding for MySQL and PostgreSQL

.gitignore, weatherforecast-csharp/Program.cs, weatherforecast-csharp/config/workload.yaml, weatherforecast-steeltoe/Program.cs, weatherforecast-steeltoe/Sample.csproj, weatherforecast-steeltoe/config/workload.yaml
=> Update csharp apps to fix swagger when deployed, prevent scale to 0

appsso-starter-java/build.gradle, java-function/cloudevents/build.gradle, java-rest-service/build.gradle.kts, java-rest-service/pom.xml, java-server-side-ui/build.gradle.kts, java-server-side-ui/pom.xml, spring-cloud-serverless/pom.xml, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml, tanzu-java-web-app/pom.xml, where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
Also upgrade related Spring Cloud dependencies
Fix https://github.com/pivotal/acc-content/issues/56
=> Upgrade all Spring samples to Spring Boot 2.7.5

where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/resources/AvailabilityResource.java, where-for-dinner/where-for-dinner-availability/src/main/resources/application.yaml
Adding a simple app version api.  Addresses issue #129
=> Adding simple API to where for dinner availability for inner loop tests.

where-for-dinner/templates/knEventing.yaml, where-for-dinner/templates/workloads.yaml, where-for-dinner/where-for-dinner-availability/config/workload.yaml
=> Fixing cloud events in TAP 1.4.

java-rest-service/accelerator.yaml
Fix https://github.com/vmware-tanzu/application-accelerator-samples/issues/137
=> Only display database options that relate to selected database

fragments/live-update/Tiltfile, java-function/Tiltfile, node-function/Tiltfile, spring-cloud-serverless/kubernetes/tap/Tiltfile, spring-smtp-gateway/smtp-gateway/Tiltfile, spring-smtp-gateway/smtp-sink/Tiltfile, tanzu-java-web-app/Tiltfile, weatherforecast-steeltoe/Tiltfile, where-for-dinner/where-for-dinner-api-gateway/Tiltfile, where-for-dinner/where-for-dinner-availability/Tiltfile, where-for-dinner/where-for-dinner-notify/Tiltfile, where-for-dinner/where-for-dinner-search-proc/Tiltfile, where-for-dinner/where-for-dinner-search/Tiltfile
To use "--update-strategy replace"
=> feat: update tiltfiles

fragments/java-version/accelerator.yaml
=> Use string value for java version in workload.yaml

spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml
Signed-off-by: Thomas Risberg <risbergt@vmware.com>
=> Update boot and commons-net versions for spring-smtp-gateway

where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
=> Removed reference to spring release repo in where for dinner in main branch.

where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
=> Removing references to spring releases repository in where for dinner in 1.4.x branch.

where-for-dinner/where-for-dinner-availability/config/workload.yaml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
=> Removing reference to spring release repo in where for dinner in 1.3.x branch.

appsso-starter-java/README.md, appsso-starter-java/client.yaml
Changes are to simplify external use of client.yaml with ytt. 'Secure a Workload' docs instruct the end-user on how to apply this resource.
=> Updates client.yaml for appsso-starter-java

where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-notify/src/main/java/com/java/example/tanzu/wherefordinner/publisher/EmailPublisher.java, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
- upgrade spring to 3.0.2
- upgrade java 17
- remove repo.spring.io
=> Remove repo.spring.io from where-for-dinner

fragments/java-version/accelerator.yaml, java-rest-service/accelerator.yaml, java-rest-service/build.gradle.kts, java-rest-service/pom.xml, tanzu-java-web-app/accelerator.yaml, tanzu-java-web-app/config/workload.yaml, tanzu-java-web-app/pom.xml, tanzu-java-web-app/src/main/java/com/example/springboot/Application.java
- include java-rest-service
- include tanzu-java-web-app
=> Add processing to update select accelerators to use Spring Boot 3.0

appsso-starter-java/README.md, appsso-starter-java/build.gradle, appsso-starter-java/client.yaml, appsso-starter-java/config/workload.yaml, appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/AuthenticationCheckFilter.java, appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/WebSecurityConfig.java, appsso-starter-java/src/main/resources/application-local.yml, appsso-starter-java/src/test/java/com/vmware/tanzu/apps/sso/accelerator/AppSSOAcceleratorApplicationTest.java
=> adds support for Spring Boot 3 in appsso-starter-java accelerator

where-for-dinner/where-for-dinner-search-proc/pom.xml
Found an issue with the declarative http client.
=> Rolling back where for dinner search-proc app to SpringBoot 3.0.2

angular-frontend/AUTHORIZATION.md, angular-frontend/README.md, angular-frontend/accelerator.yaml, angular-frontend/angular.json, angular-frontend/config/clientregistration.yaml, angular-frontend/package-lock.json, angular-frontend/package.json, angular-frontend/src/app/app-config.service.ts, angular-frontend/src/app/app-routing.module.ts, angular-frontend/src/app/app.module.ts, angular-frontend/src/app/authorization/AuthorizationTypes.ts, angular-frontend/src/app/authorization/authInterceptor.spec.ts, angular-frontend/src/app/authorization/authInterceptor.ts, angular-frontend/src/app/authorization/authentication-utilities.spec.ts, angular-frontend/src/app/authorization/authentication-utilities.ts, angular-frontend/src/app/authorization/authorization-config.ts, angular-frontend/src/app/authorization/authorization.service.spec.ts, angular-frontend/src/app/authorization/authorization.service.ts, angular-frontend/src/app/configTypes.ts, angular-frontend/src/app/user-profile/user-profile.component.html, angular-frontend/src/app/user-profile/user-profile.component.spec.ts, angular-frontend/src/app/user-profile/user-profile.component.ts, angular-frontend/src/app/user-profile/user-profile.module.ts, angular-frontend/src/app/user-profile/user-profile.service.spec.ts, angular-frontend/src/app/user-profile/user-profile.service.ts, angular-frontend/src/app/utils.spec.ts, angular-frontend/src/app/utils.ts, angular-frontend/src/assets/auth.conf.json, angular-frontend/src/polyfills.ts, angular-frontend/tsconfig.json
This pull request adds an AppSSO integration to the Angular frontend. It is optional to add through the `tap-gui`. 
- Updated the `accelerator.yaml` to conditionally add authorization
- Added an `AUTHORIZATION.md` to help guide the user through the authorization process
- Adds a path for user profile information
- Adds an interceptor that redirects to the authserver for signin if there is no token and adds the token to the request if it is present.
- Added unit tests
=> feat: add oauth2 single sign-on

java-function/DEPLOYING.md, python-function/DEPLOYING.md
Function Buildpacks builder was recently updated.  This PR updates that version in the function docs.
=> chore(docs) Update builder version

.github/workflows/scan.yaml, appsso-starter-java/build.gradle, java-function/cloudevents/build.gradle, java-rest-service/accelerator.yaml, java-rest-service/build.gradle.kts, java-rest-service/pom.xml, java-server-side-ui/build.gradle.kts, java-server-side-ui/pom.xml, node-function/package-lock.json, spring-cloud-serverless/pom.xml, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml, tanzu-java-web-app/accelerator.yaml, tanzu-java-web-app/pom.xml, where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
Prerequisite for https://github.com/pivotal/acc-release/issues/490
=> Update to latest patch releases and fix CVEs

csharp-rest-service/RestService.csproj, weatherforecast-steeltoe/Sample.csproj
Addresses grype report:
```
NAME                            INSTALLED  FIXED-IN  TYPE    VULNERABILITY        SEVERITY 
System.Net.Http                 4.3.0      4.3.4     dotnet  GHSA-7jgj-8wvc-jh57  High      
System.Text.RegularExpressions  4.3.0      4.3.1     dotnet  GHSA-cmhx-cq75-c4mj  High      
```
=> fix .NET vulnerabilities

angular-frontend/accelerator.yaml, angular-frontend/src/app/app-routing.module.ts, angular-frontend/src/app/app.module.ts
Able to successfully replicate the bug in question as per issue #220.
Fix verified generating two copies of angular-frontend accelerator (without sso, with sso) and running the following: 
```shell
npm install
ng build
ng test
```
Resolves #220
=> fix compilation issue with sso integration in angular-frontend accelerator

where-for-dinner/where-for-dinner-api-gateway/src/main/java/com/java/example/tanzu/wherefordinner/DinnerAPIGatewayApplication.java
Addressing issue #224 for TAP 1.5.1
=> Resolving redirect issue with AppSSO and API Gateway.

weatherforecast-csharp/accelerator.yaml, weatherforecast-steeltoe/README.md, weatherforecast-steeltoe/accelerator.yaml
This branch is mean to test accelerator with ASA.
=> replace "-" with "_" in namespaces in C# projects

where-for-dinner/doc/TAPDeployment.md, where-for-dinner/templates/dyanmicRabbitMQCluster.yaml, where-for-dinner/templates/dynamicMySqlInstance.yaml, where-for-dinner/templates/dynamicRedisInstance.yaml, where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
Simplifying the compositions to remove objects that are not needed such as secret template, secret export, and secret import.
Also updating apps to SpringBoot 3.0.6
Submitting as part of #245
=> Updating WFD CrossPlane composition to remove secret templates

spring-smtp-gateway/accelerator.yaml
Not sure if this was lost in some recent changes, but it is included in main branch
=> Include README for spring-smtp-gateway

where-for-dinner/templates/appSSOInstance.yaml
=> Swithing TLS setting from disabled to deactived

where-for-dinner/templates/dyanmicRabbitMQCluster.yaml, where-for-dinner/templates/dynamicMySqlInstance.yaml, where-for-dinner/templates/dynamicRedisInstance.yaml
=> Adding RBAC permissions to Where For Dinner Crossplane compositions

.github/tests/tanzu-java-web-app-boot2/assertions.sh, .github/tests/tanzu-java-web-app-boot2/options.json, .github/tests/tanzu-java-web-app-boot2_gradle/assertions.sh, .github/tests/tanzu-java-web-app-boot2_gradle/options.json, .github/tests/tanzu-java-web-app-boot3/assertions.sh, .github/tests/tanzu-java-web-app-boot3_gradle_intellij/assertions.sh, .github/tests/tanzu-java-web-app-boot3_gradle_intellij/options.json, .github/tests/tanzu-java-web-app-boot3_gradle_vscode/assertions.sh, .github/tests/tanzu-java-web-app-boot3_gradle_vscode/options.json, .github/tests/tanzu-java-web-app-boot3_native/assertions.sh, .github/tests/tanzu-java-web-app-boot3_native/options.json, .github/tests/tanzu-java-web-app-boot3_native/scan.sh, tanzu-java-web-app/README-native.md, tanzu-java-web-app/README.md, tanzu-java-web-app/accelerator.yaml, tanzu-java-web-app/pom.xml
- Add option to support native builds
- Update tests for nativeBuild option
=> Update Tanzu Java Web App to support GraalVM native builds

java-server-side-ui/build.gradle.kts, java-server-side-ui/pom.xml
=> Update Spring Boot version

spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml, where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
Addressing issues #270 and #271
=> Updating smtp gateway and where for dinner to latest boot patch release

angular-frontend/package-lock.json
=> Changes based on 'npm audit fix'

.github/tests/tanzu-java-web-app-boot3/options.json, .github/tests/tanzu-java-web-app-boot3_gradle_intellij/options.json, .github/tests/tanzu-java-web-app-boot3_gradle_vscode/options.json, .github/tests/tanzu-java-web-app-boot3_native/options.json, tanzu-java-web-app/accelerator.yaml, tanzu-java-web-app/build.gradle.kts, tanzu-java-web-app/pom.xml
=> Add Spring Boot 3.1 option

where-for-dinner/templates/workloadRegistrationResourceClaim.yaml
Updating URI to "/login/oauth2/code/sso."  Addressing issue #289
=> Fixing where for dinner redirect URI.

appsso-starter-java/build.gradle, appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/IssuerTrust.java, appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/WebSecurityConfig.java
Fixed up deprecated Spring constructs as part of these changes.
Closes #267
=> Bump appsso-starter-java to Spring Boot 3.1.0

ns-provisioner-samples/gitops-install-params-sa/desired-namespaces.yaml, ns-provisioner-samples/gitops-install-params-sa/namespaces.yaml
Add an example of how should be the install from GitOps adding secrets to the default service account
=> chore: Add NSP GitOps install sample with SA customization

where-for-dinner/where-for-dinner-availability/src/main/resources/application.yaml, where-for-dinner/where-for-dinner-notify/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search/src/main/resources/application.yml, where-for-dinner/where-for-dinner-ui/config/workload.yaml
PRs addressing issues #293 and #297 which includes disabling RabbitMQ auto config.
=> Fixing subpath in WFD UI application's workload.yaml file (TAP 1.5.x)

where-for-dinner/where-for-dinner-availability/src/main/resources/application.yaml, where-for-dinner/where-for-dinner-notify/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search/src/main/resources/application.yml, where-for-dinner/where-for-dinner-ui/config/workload.yaml
PRs addressing issues #293 and #297 which includes disabling RabbitMQ auto config.
=> Fixing subpath in WFD UI application's workload.yaml file.

java-function/cloudevents/build.gradle, java-function/cloudevents/pom.xml
Addresses CVEs discovered in grype scans
=> Update dependencies in java function sample

tanzu-java-web-app/pom.xml
- will allow GraalVM native build with Boot 3.1
=> Remove dev-tools dependency

spring-smtp-gateway/README.md, spring-smtp-gateway/accelerator.yaml, spring-smtp-gateway/smtp-gateway/config/workload.yaml, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/server/GetMessageHeaderStream.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/server/SMTPMailMessage.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/server/SMTPMessageHandler.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/server/SizeLimitedStreamCreator.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/streams/SMTPMailMessageConverter.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/streams/SmtpGatewayMessageSource.java, spring-smtp-gateway/smtp-gateway/src/main/java/com/java/example/smtpmq/gateway/task/SimulatedLoadTask.java, spring-smtp-gateway/smtp-gateway/src/main/resources/application.yml, spring-smtp-gateway/smtp-gateway/src/test/java/com/java/example/smtpmq/gateway/boot/SMTPMessageHandler_largeRecipsTest.java, spring-smtp-gateway/smtp-gateway/src/test/java/com/java/example/smtpmq/gateway/boot/SMTPMessageHandler_sendMessageTest.java, spring-smtp-gateway/smtp-sink/config/workload.yaml, spring-smtp-gateway/smtp-sink/pom.xml, spring-smtp-gateway/smtp-sink/src/main/java/com/java/example/smtpsink/functions/SMTPMailMessage.java, spring-smtp-gateway/smtp-sink/src/main/java/com/java/example/smtpsink/functions/SMTPMailMessageConverter.java, spring-smtp-gateway/smtp-sink/src/main/java/com/java/example/smtpsink/functions/SMTPMessageSink.java, spring-smtp-gateway/smtp-sink/src/main/resources/application.yml, spring-smtp-gateway/templates/workloads.template, where-for-dinner/where-for-dinner-availability/src/main/resources/application.yaml, where-for-dinner/where-for-dinner-notify/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search/src/main/resources/application.yml, where-for-dinner/where-for-dinner-ui/config/workload.yaml
Addressing issues #304 and #303.
=> Adding Kafka support and upgrading to Boot 3.1.x in SMTP app.

.github/tests/.grype.yaml, .github/tests/spring-smtp-gateway-1/options.json, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml
=> Updating SMTP gateway samples to spring boot 3.1.1.

where-for-dinner/templates/knEventing.yaml, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/entity/Availability.java, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/function/AvailabilitySink.java, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/model/Search.java, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/repository/AvailabilityWindowRepository.java, where-for-dinner/where-for-dinner-availability/src/main/resources/application.yaml, where-for-dinner/where-for-dinner-availability/src/test/java/com/java/example/tanzu/wherefordinner/SpringBaseTest.java, where-for-dinner/where-for-dinner-availability/src/test/java/com/java/example/tanzu/wherefordinner/function/AvailabilitySink_processDeletedSearchTest.java, where-for-dinner/where-for-dinner-search/src/main/java/com/java/example/tanzu/wherefordinner/resources/SearchResource.java, where-for-dinner/where-for-dinner-search/src/main/resources/application.yml
=> Fixing orphaned available rows in Where For DInner

tanzu-java-web-app/accelerator.yaml
=> Fix Java/Boot version logic

fragments/devcontainer/.devcontainer.json, fragments/devcontainer/README-devcontainer.md
Added setting to set java lang server mode to standard
=> Updated devcontainer fragment

where-for-dinner/accelerator.yaml, where-for-dinner/templates/ingress.yaml, where-for-dinner/templates/workloads.yaml
=> Adding server workload type support.

spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
Used in SMTP gateway and Where For Dinner as part of the Kafka dependency.
=> Mitigating CVE-2023-43642 in snappy-java component.

fragments/devcontainer/.devcontainer.json
* Updated devcontainer fragment image version to fix an issue when running live update
=> Update devcontainer fragment image version

appsso-starter-java/accelerator.yaml, fragments/app-sso-client/accelerator.yaml
- Make `appssoOfferingName` required in `app-sso-client` fragment
- Use `app-sso-client` fragment in `appsso-starter-java`
=> Fix appssoOfferingName option

where-for-dinner/doc/TAPDeployment.md, where-for-dinner/templates/rmqCluster.yaml
=> Mitigating Pod Security Admission issues with RabbitMQ OSS operator.

where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search-proc/src/main/resources/application.yml, where-for-dinner/where-for-dinner-search/pom.xml
=> Updating to WFD to Spring Cloud Bindings 2.x.  

appsso-starter-java/build.gradle, java-rest-service/build.gradle.kts, java-rest-service/pom.xml, spring-cloud-serverless/pom.xml
=> Update to use Spring Boot 3.1.6

react-frontend/package-lock.json, react-frontend/package.json
Make latest axios cope with jest
=> Latest axios with jest

where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
=> Updating Where For Dinner to Spring Boot 3.2.0

spring-streaming-app/pom.xml
=> Updating spring streaming app to Spring Boot 3.2.

appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/WebSecurityConfig.java
instead let the user be redirected to the login page
=> fix: do not redirect to /home when accessing private pages

appsso-starter-java/src/main/java/com/vmware/tanzu/apps/sso/accelerator/config/WebSecurityConfig.java
Single logout does not work with AppSSO. Remove the code from the client.
=> AppSSO: remove single-logout

angular-frontend/package-lock.json, angular-frontend/package.json, where-for-dinner/where-for-dinner-api-gateway/config/workload.yaml, where-for-dinner/where-for-dinner-availability/config/workload.yaml, where-for-dinner/where-for-dinner-crawler/config/workload.yaml, where-for-dinner/where-for-dinner-notify/config/workload.yaml, where-for-dinner/where-for-dinner-search-proc/config/workload.yaml, where-for-dinner/where-for-dinner-search/config/workload.yaml, where-for-dinner/where-for-dinner-ui/package-lock.json, where-for-dinner/where-for-dinner-ui/package.json
These were missed as part of issue #403.
=> Updating individual workload.yaml files to use Java 21 in WFD.

where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/config/DBTransactionRouteConfig.java, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/function/AvailabilitySink.java, where-for-dinner/where-for-dinner-availability/src/main/java/com/java/example/tanzu/wherefordinner/resources/AvailabilityResource.java, where-for-dinner/where-for-dinner-availability/src/main/java/org/springframework/cloud/bindings/boot/OAuth2BindingsPropertiesProcessor.java, where-for-dinner/where-for-dinner-availability/src/main/java/org/springframework/cloud/bindings/boot/PostgreSqlReadBindingsPropertiesProcessor.java, where-for-dinner/where-for-dinner-availability/src/main/resources/META-INF/spring.factories, where-for-dinner/where-for-dinner-availability/src/main/resources/application.yaml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search-proc/src/main/java/com/java/example/tanzu/wherefordinner/processor/SearchProcessor.java, where-for-dinner/where-for-dinner-search/pom.xml, where-for-dinner/where-for-dinner-search/src/main/java/com/java/example/tanzu/wherefordinner/config/DBTransactionRouteConfig.java, where-for-dinner/where-for-dinner-search/src/main/java/com/java/example/tanzu/wherefordinner/functions/SearchSupplier.java, where-for-dinner/where-for-dinner-search/src/main/java/com/java/example/tanzu/wherefordinner/resources/SearchResource.java, where-for-dinner/where-for-dinner-search/src/main/java/org/springframework/cloud/bindings/boot/OAuth2BindingsPropertiesProcessor.java, where-for-dinner/where-for-dinner-search/src/main/java/org/springframework/cloud/bindings/boot/PostgreSqlReadBindingsPropertiesProcessor.java, where-for-dinner/where-for-dinner-search/src/main/resources/META-INF/spring.factories, where-for-dinner/where-for-dinner-search/src/main/resources/application.yml
Also fixing issues in stream processors when errors are thrown and causing stream functions to no longer work.
This addresses issue #420
=> Adding support for read only DB endpoints in Where For Dinner.

spring-ai-chat/README.md, spring-ai-chat/accelerator.yaml, spring-ai-chat/catalog/catalog-info.yaml, spring-ai-chat/config/workload.yaml
- add catalog-info.yaml
- fix workload name and
- update README
- switch to use a secret for AI API key
=> Some tweaks for spring-ai-chat

fragments/spring-boot-app-sso-auth-code-flow/accelerator.yaml, fragments/spring-boot-app-sso-auth-code-flow/src/main/java/com/vmware/tap/fragments/appssoauthcodeflow/WebSecurityConfiguration.java, fragments/spring-boot-app-sso-auth-code-flow/src/main/resources/templates/protected/profile.html, java-server-side-ui/build.gradle.kts, java-server-side-ui/pom.xml
Closes: gh-422
Implemented similar changes to appsso-starter-java:
- Remove thymeleaf-springsecurity
- Remove (unsupported) OIDC single-logout
See gh-399 & gh-408.
=> java-server-side-ui: bump to boot 3.2.3

angular-frontend/package-lock.json, angular-frontend/package.json, react-frontend/package-lock.json, react-frontend/package.json, where-for-dinner/where-for-dinner-ui/package-lock.json, where-for-dinner/where-for-dinner-ui/package.json
=> Addressing CVE GHSA-wr3j-pwj9-hqq6

spring-ai-chat/pom.xml, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/AIConfig.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/ChatController.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/memory/ConversationBufferMemory.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/memory/Memory.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/operator/AiOperator.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/operator/DefaultAiOperator.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/operator/DefaultAiOperatorBuilder.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/operator/DefaultPromptTemplateStrings.java, spring-ai-chat/src/main/resources/static/actions.js, spring-ai-chat/src/main/resources/static/style.css, spring-ai-chat/src/main/resources/templates/home.html
Including:
- Upgrade to Spring AI 0.8.1
- Refactor operator and memory packages under project package instead of `org.springframework.ai.*`
- Tweak RAG prompt to avoid mention of DOCUMENTS section in response
- Make upload dialog truly modal and add spinner to display while upload is in progress
=> Several modifications

spring-secure-resource-server/accelerator.yaml, spring-secure-resource-server/audit/pom.xml, spring-secure-resource-server/postal-code-search/pom.xml
- Add tap-workload fragment for all config.yaml files
- Add micrometer prometheus dependency for secure resource server
=> Update secure resource server

tanzu-java-web-app/build.gradle.kts, tanzu-java-web-app/pom.xml
-  this was causing build failures when testing with tanzu build
=> Update java version in tanzu-java-web-app

csharp-rest-service/RestService.csproj, fragments/steeltoe-postgresql/README.md
Also fix steeltoe-postgres fragment readme to reference Steeltoe instead of Spring Boot
=> C# Rest Service upgrade to .NET and Npgsql 8.0

spring-smtp-gateway/smtp-gateway/config/workload.yaml, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/config/workload.yaml, spring-smtp-gateway/smtp-sink/pom.xml, spring-smtp-gateway/templates/workloads.template
Updating all apps to newer version of Spring Boot, Spring Cloud, and Java.  Also updated workload.yaml files to use Java 21.
=> Updating smtp gateway to Boot 3.3.0, java 21, Cloud 2023.0.2

fragments/spring-boot-database/accelerator.yaml, java-rest-service/build.gradle.kts, java-rest-service/pom.xml
A less invasive update - alternative to #494
=> Update java-rest-service to Spring Boot 3.3.0

appsso-starter-java/build.gradle, java-rest-service/build.gradle.kts, java-rest-service/pom.xml, java-server-side-ui/build.gradle.kts, java-server-side-ui/pom.xml, spring-ai-chat/pom.xml, spring-cloud-serverless/pom.xml, spring-secure-resource-server/audit/pom.xml, spring-secure-resource-server/postal-code-client/pom.xml, spring-secure-resource-server/postal-code-search/pom.xml, spring-smtp-gateway/smtp-gateway/pom.xml, spring-smtp-gateway/smtp-sink/pom.xml, spring-streaming-app/pom.xml, tanzu-java-web-app/build.gradle.kts, tanzu-java-web-app/pom.xml, where-for-dinner/where-for-dinner-api-gateway/pom.xml, where-for-dinner/where-for-dinner-availability/pom.xml, where-for-dinner/where-for-dinner-crawler/pom.xml, where-for-dinner/where-for-dinner-notify/pom.xml, where-for-dinner/where-for-dinner-search-proc/pom.xml, where-for-dinner/where-for-dinner-search/pom.xml
- Spring Boot to 3.3.2
- Spring Cloud to 2023.0.3
=> Update Spring Boot and Spring Cloud to latest version

where-for-dinner/where-for-dinner-ui/package-lock.json, where-for-dinner/where-for-dinner-ui/package.json
Addressing vulnerability in older version.
=> fix: Updating rollup package in WFD UI to 3.29.5.

spring-ai-chat/pom.xml, spring-music/build.gradle, tanzu-java-web-app/build.gradle.kts, tanzu-java-web-app/pom.xml
- spring-cloud to 2024.0.0
- buildtools native 0.10.4
=> Update samples to use Spring Boot 3.4.1

.github/tests/spring-ai-chat-defaults/assertions.sh, .github/tests/spring-ai-chat-projectcoords/assertions.sh, spring-ai-chat/README.md, spring-ai-chat/accelerator.axl, spring-ai-chat/accelerator.yaml, spring-ai-chat/pom.xml, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/ChatController.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/SimpleVectorStoreConfig.java, spring-ai-chat/src/main/java/com/vmware/tap/accelerators/aichat/UploadController.java, spring-ai-chat/src/main/resources/application.properties
=> Update Spring AI Chat to Spring AI 1.0.0-RC1
